function(maker_utils_debug message)
  set(MAKER_PRINT_DEBUG 0 CACHE BOOL "Turn on maker debugging")
#  if(${MAKER_PRINT_DEBUG})
    message(${message})			  
#     endif()
endfunction()

macro(maker_utils_require_abs abs_file)
  if (NOT DEFINED maker_utils_require_${abs_file})
    set(maker_utils_require_${abs_file} 1)
    include(${abs_file})
  else()
    maker_utils_debug("already included ${abs_file}")
  endif()
endmacro()

macro(maker_utils_require relative_file)
  maker_utils_require_abs(${CMAKE_CURRENT_LIST_DIR}/${relative_file}) 
endmacro()

macro(maker_utils_include_nonexcl relative_file)
      include(${CMAKE_CURRENT_LIST_DIR}/${relative_file}) 
endmacro()